- name: course information
  hosts: local
  connection: local
  vars:
    course: "DevSecOps with AIOps"
    duration_in_hrs: 150
    is_live_sessions: true
    topics: # list
    - linux
    - shell
    - ansible
    more_details:
      months: "5"
      trainer: "sivakumar"
  tasks:
  - name: print information
    debug:
      msg: |
        name: {{ course }}
        duration: {{ duration_in_hrs }}
        is_it_live: {{ is_live_sessios }}
        topics: {{ topics }}
        more_deatils: {{ more_deatils }}